# Generated by Django 4.2.7 on 2023-12-10 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="num_guests",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="number of extra guests",
            ),
        ),
    ]
