# Generated by Django 5.0.3 on 2026-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_contactlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleOAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("token_json", models.JSONField()),
                ("updated_ts", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
