# Generated by Django 5.0.3 on 2025-08-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
