# Generated by Django 5.0.3 on 2025-08-21 01:39

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    for post in Post.objects.all():
        post.slug = slugify(post.title)
        post.save()


def depopulate_slugs(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    for post in Post.objects.all():
        post.slug = None
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_slug"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, depopulate_slugs),
    ]
