# Generated by Django 5.0.3 on 2025-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_populate_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
